#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#44475a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

$HOME/.config/polybar/launch.sh
nitrogen --restore
#synclient tapbutton2=3
light -S 30
light -s sysfs/leds/smc::kbd_backlight -S 0
