#!/bin/bash

sxhkd -c ~/.config/berry/sxhkdrc &
nitrogen --restore &
~/.config/polybar/launch.sh &
~/.config/berry/renamews.sh &
nm-applet &

 xset +fp /home/jona/.local/share/fonts
    xset fp rehash


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       1
berryc top_gap            26

# Set decoration colors   
berryc focus_color         2e3440
berryc unfocus_color       2e3440
berryc inner_focus_color   88c0d0
berryc inner_unfocus_color 5381ac
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "fals"
berryc edge_lock   "true"
berryc set_font    "Dina-9"
